const { withAppBuildGradle } = require('expo/config-plugins');

// Wires android/app/build.gradle to sign release builds with a real upload
// keystore instead of the debug key. android/ itself is gitignored and fully
// regenerated by `expo prebuild` (see CLAUDE.md "Build notes"), so this has
// to run as a config plugin rather than a one-time manual edit — otherwise
// every prebuild would quietly undo it and releases would go back to being
// debug-signed.
//
// Secrets never enter this file or git: they live in
// android/keystore.properties (gitignored — see keystore.properties.example
// for the four keys it needs), read at Gradle-configure time. Until that
// file exists, release builds still fall back to the debug key, so a fresh
// checkout with no keystore set up keeps building.
const SIGNING_CONFIGS_ANCHOR = 'signingConfigs {';
const RELEASE_COMMENT_ANCHOR = `            // Caution! In production, you need to generate your own keystore file.
            // see https://reactnative.dev/docs/signed-apk-android.
            signingConfig signingConfigs.debug`;

const KEYSTORE_LOADER = `
def keystorePropertiesFile = rootProject.file("keystore.properties")
def keystoreProperties = new Properties()
if (keystorePropertiesFile.exists()) {
    keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
}
`;

const RELEASE_SIGNING_CONFIG = `${SIGNING_CONFIGS_ANCHOR}
        release {
            if (keystorePropertiesFile.exists()) {
                storeFile file(keystoreProperties['RELEASE_STORE_FILE'])
                storePassword keystoreProperties['RELEASE_STORE_PASSWORD']
                keyAlias keystoreProperties['RELEASE_KEY_ALIAS']
                keyPassword keystoreProperties['RELEASE_KEY_PASSWORD']
            }
        }`;

const RELEASE_SIGNING_USE = `            // Caution! In production, you need to generate your own keystore file.
            // see https://reactnative.dev/docs/signed-apk-android.
            signingConfig keystorePropertiesFile.exists() ? signingConfigs.release : signingConfigs.debug`;

module.exports = function withReleaseSigning(config) {
  return withAppBuildGradle(config, (config) => {
    let contents = config.modResults.contents;

    if (contents.includes('keystorePropertiesFile')) {
      // Already patched — a re-run on a tree that wasn't cleaned.
      return config;
    }

    if (!contents.includes('apply plugin: "com.android.application"')) {
      throw new Error(
        'withReleaseSigning: expected `apply plugin: "com.android.application"` not found in ' +
          'android/app/build.gradle. The Expo/RN Android template changed shape — update ' +
          'plugins/withReleaseSigning.js to match.',
      );
    }
    contents = contents.replace(
      'apply plugin: "com.android.application"',
      `apply plugin: "com.android.application"\n${KEYSTORE_LOADER}`,
    );

    if (!contents.includes(SIGNING_CONFIGS_ANCHOR)) {
      throw new Error(
        'withReleaseSigning: expected `signingConfigs {` block not found in android/app/build.gradle. ' +
          'Update plugins/withReleaseSigning.js to match the current template.',
      );
    }
    contents = contents.replace(SIGNING_CONFIGS_ANCHOR, RELEASE_SIGNING_CONFIG);

    if (!contents.includes(RELEASE_COMMENT_ANCHOR)) {
      throw new Error(
        'withReleaseSigning: expected release buildType signingConfig block not found in ' +
          'android/app/build.gradle. Update plugins/withReleaseSigning.js to match the current template.',
      );
    }
    contents = contents.replace(RELEASE_COMMENT_ANCHOR, RELEASE_SIGNING_USE);

    config.modResults.contents = contents;
    return config;
  });
};
